### ISSUE TITLE
Toy example how to use the code ? 

### ISSUE THREAD

**Issue by sabirdvd** [israa-alghanmi/BERT-GloVe#1]
Thank you for sharing your work. I like this idea, straightforward and robust against overfitting. Could you please provide a toy example of how to use this code (i.e., training, inference)? 

Another work is similar,  Maybe your interested on, called Top modeling-BERT https://www.aclweb.org/anthology/2020.acl-main.630.pdf 

Also, version of each of the *requirements.txt* (TF 2.0, ... ) python 3 or 2 

Thank you in advance.

**Comment by israa-alghanmi** [comment]
Thank you for your comment and for sharing the paper. A very interesting read!

Here are the versions
Python —> 3.7
TensorFlow —> 2.3
I will try to provide an example, although, due to the large size of the fine-tuned BERT checkpoint, it might not be feasible.

**Comment by sabirdvd** [comment]
Thank you for your response. Toy example means: you take a subset from the dataset (Eng) and make the code runnable. For instance, you take 10 samples from (each) the training/val/test English dataset and upload the file. No need to share the BERT weight, just the empty file to show which files the model/code expected. The idea  to provide a toy example of how to use this code (i.e., training, inference).

Another idea for future work, you could convert Bert to a static embedding [1] and concatenating it with Glove as Meta-Embeddings.

[1] https://openreview.net/pdf?id=SJg3T2EFvr
