### ISSUE TITLE
Hi i wonder why not report the resullts of joint-learning?

### ISSUE THREAD

**Issue by Anothernewcomer** [israa-alghanmi/BERT-GloVe#2]
As you mentioned in the paper"After this fine-tuning step, we freeze the BERT model and train the CNN and combined classification layer. We found this strategy to be more robust against over-fitting." My situation is that I have already fine-tuned a BERT model, and 
recently wanting to add some other features using GCN and concat it with BERT embeddings（as BERT can not handle graph format data). I never tried this model structure before then I saw your work and think it may suit me. But I still wonder wheather it is the same(or almost the same) to finetune BERT at the same time and finetune BERT beforehand?  Thanks for your reply ！

**Comment by israa-alghanmi** [comment]
You could try both, but for this work, we observed that using static word embeddings and fine-tuning LM would require different sets of hyperparameters, so doing joint learning might cause underfitting or overfitting.
